version: '3'
services:

  db:
    image: postgres
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"

  redis:
    container_name: redis
    image: redis:3.2.0
    expose:
      - "6379"
    volumes:
      - ./data/redis-data:/data
    command: redis-server
  
  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    links:
      - django:django
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  django:
    build: .
    image: corona_plots:latest
    command: sh runserver.sh
    links:
      - redis:redis
      - db:db
    expose:
      - "8080"
    volumes:
      - ./backend/src:/opt/coronavirus_plot_web
    depends_on:
      - db
      - redis
  
  celery:
    image: corona_plots:latest
    links: 
      - redis:redis
    environment:
      - CELERY_BROKER_URL=redis://redis
    volumes:
      - ./backend/src:/opt/coronavirus_plot_web
    command: celery worker -A djreact -B -l info
    depends_on:
      - django
      - redis
      - db